version: '3'

tasks:

  data:unzip:
    desc: Unzip debate corpus
    dir: data
    cmds:
      - tar -xf UNGDC_1946-2022.tgz
  
  data:preprocess:
    desc: Save preprocessed versions of the raw data (joining metadata with speeches, chunking speeches, etc)
    cmds:
      - poetry run python scripts/preprocess.py

  vector-db:start:
    desc: Start qdrant vector db
    cmds:
      - docker run -d -p 6333:6333 -p 6334:6334 -v $(pwd)/qdrant_storage:/qdrant/storage:z qdrant/qdrant:latest

  vector-db:index:
    desc: Index data in the vector db
    cmds:
      - poetry run python scripts/index.py --no-subset
    
  vector-db:index-subset:
    desc: Index data in the vector db (subset for testing purposes)
    cmds:
      - poetry run python scripts/index.py --subset

  app:run:
    desc: Run streamlit app for QA experience
    cmds:
      - poetry run streamlit run app.py
